// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as workflowsRouteImport } from "./routes/workflows";
import { Route as watchFloorRouteImport } from "./routes/watch-floor";
import { Route as tuningRouteImport } from "./routes/tuning";
import { Route as settingsRouteImport } from "./routes/settings";
import { Route as remindersRouteImport } from "./routes/reminders";
import { Route as pulseRouteImport } from "./routes/pulse";
import { Route as projectsRouteImport } from "./routes/projects";
import { Route as policyRouteImport } from "./routes/policy";
import { Route as ledgerRouteImport } from "./routes/ledger";
import { Route as leasesRouteImport } from "./routes/leases";
import { Route as handoffRouteImport } from "./routes/handoff";
import { Route as gapsRouteImport } from "./routes/gaps";
import { Route as agentsRouteImport } from "./routes/agents";
import { Route as indexRouteImport } from "./routes/index";
import { Route as workflowsDotworkflowIdRouteImport } from "./routes/workflows.$workflowId";
import { Route as projectsDotprojectIdRouteImport } from "./routes/projects.$projectId";
import { Route as messagesDotnewRouteImport } from "./routes/messages.new";
import { Route as lanesDotlaneIdRouteImport } from "./routes/lanes.$laneId";
import { Route as channelsDotchannelIdRouteImport } from "./routes/channels.$channelId";
import { Route as casesDotcaseIdRouteImport } from "./routes/cases.$caseId";
import { Route as channelsDotchannelIdDotpostsDotpostIdRouteImport } from "./routes/channels.$channelId.posts.$postId";

const workflowsRoute = workflowsRouteImport.update({
  id: "/workflows",
  path: "/workflows",
  getParentRoute: () => rootRouteImport,
} as any);
const watchFloorRoute = watchFloorRouteImport.update({
  id: "/watch-floor",
  path: "/watch-floor",
  getParentRoute: () => rootRouteImport,
} as any);
const tuningRoute = tuningRouteImport.update({
  id: "/tuning",
  path: "/tuning",
  getParentRoute: () => rootRouteImport,
} as any);
const settingsRoute = settingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const remindersRoute = remindersRouteImport.update({
  id: "/reminders",
  path: "/reminders",
  getParentRoute: () => rootRouteImport,
} as any);
const pulseRoute = pulseRouteImport.update({
  id: "/pulse",
  path: "/pulse",
  getParentRoute: () => rootRouteImport,
} as any);
const projectsRoute = projectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => rootRouteImport,
} as any);
const policyRoute = policyRouteImport.update({
  id: "/policy",
  path: "/policy",
  getParentRoute: () => rootRouteImport,
} as any);
const ledgerRoute = ledgerRouteImport.update({
  id: "/ledger",
  path: "/ledger",
  getParentRoute: () => rootRouteImport,
} as any);
const leasesRoute = leasesRouteImport.update({
  id: "/leases",
  path: "/leases",
  getParentRoute: () => rootRouteImport,
} as any);
const handoffRoute = handoffRouteImport.update({
  id: "/handoff",
  path: "/handoff",
  getParentRoute: () => rootRouteImport,
} as any);
const gapsRoute = gapsRouteImport.update({
  id: "/gaps",
  path: "/gaps",
  getParentRoute: () => rootRouteImport,
} as any);
const agentsRoute = agentsRouteImport.update({
  id: "/agents",
  path: "/agents",
  getParentRoute: () => rootRouteImport,
} as any);
const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const workflowsDotworkflowIdRoute = workflowsDotworkflowIdRouteImport.update({
  id: "/workflows/$workflowId",
  path: "/workflows/$workflowId",
  getParentRoute: () => rootRouteImport,
} as any);
const projectsDotprojectIdRoute = projectsDotprojectIdRouteImport.update({
  id: "/projects/$projectId",
  path: "/projects/$projectId",
  getParentRoute: () => rootRouteImport,
} as any);
const messagesDotnewRoute = messagesDotnewRouteImport.update({
  id: "/messages/new",
  path: "/messages/new",
  getParentRoute: () => rootRouteImport,
} as any);
const lanesDotlaneIdRoute = lanesDotlaneIdRouteImport.update({
  id: "/lanes/$laneId",
  path: "/lanes/$laneId",
  getParentRoute: () => rootRouteImport,
} as any);
const channelsDotchannelIdRoute = channelsDotchannelIdRouteImport.update({
  id: "/channels/$channelId",
  path: "/channels/$channelId",
  getParentRoute: () => rootRouteImport,
} as any);
const casesDotcaseIdRoute = casesDotcaseIdRouteImport.update({
  id: "/cases/$caseId",
  path: "/cases/$caseId",
  getParentRoute: () => rootRouteImport,
} as any);
const channelsDotchannelIdDotpostsDotpostIdRoute =
  channelsDotchannelIdDotpostsDotpostIdRouteImport.update({
    id: "/channels/$channelId/posts/$postId",
    path: "/channels/$channelId/posts/$postId",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/agents": typeof agentsRoute;
  "/gaps": typeof gapsRoute;
  "/handoff": typeof handoffRoute;
  "/leases": typeof leasesRoute;
  "/ledger": typeof ledgerRoute;
  "/policy": typeof policyRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/tuning": typeof tuningRoute;
  "/watch-floor": typeof watchFloorRoute;
  "/workflows": typeof workflowsRoute;
  "/cases/$caseId": typeof casesDotcaseIdRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/lanes/$laneId": typeof lanesDotlaneIdRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/projects/$projectId": typeof projectsDotprojectIdRoute;
  "/workflows/$workflowId": typeof workflowsDotworkflowIdRoute;
  "/channels/$channelId/posts/$postId": typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof indexRoute;
  "/agents": typeof agentsRoute;
  "/gaps": typeof gapsRoute;
  "/handoff": typeof handoffRoute;
  "/leases": typeof leasesRoute;
  "/ledger": typeof ledgerRoute;
  "/policy": typeof policyRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/tuning": typeof tuningRoute;
  "/watch-floor": typeof watchFloorRoute;
  "/workflows": typeof workflowsRoute;
  "/cases/$caseId": typeof casesDotcaseIdRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/lanes/$laneId": typeof lanesDotlaneIdRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/projects/$projectId": typeof projectsDotprojectIdRoute;
  "/workflows/$workflowId": typeof workflowsDotworkflowIdRoute;
  "/channels/$channelId/posts/$postId": typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof indexRoute;
  "/agents": typeof agentsRoute;
  "/gaps": typeof gapsRoute;
  "/handoff": typeof handoffRoute;
  "/leases": typeof leasesRoute;
  "/ledger": typeof ledgerRoute;
  "/policy": typeof policyRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/tuning": typeof tuningRoute;
  "/watch-floor": typeof watchFloorRoute;
  "/workflows": typeof workflowsRoute;
  "/cases/$caseId": typeof casesDotcaseIdRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/lanes/$laneId": typeof lanesDotlaneIdRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/projects/$projectId": typeof projectsDotprojectIdRoute;
  "/workflows/$workflowId": typeof workflowsDotworkflowIdRoute;
  "/channels/$channelId/posts/$postId": typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/agents"
    | "/gaps"
    | "/handoff"
    | "/leases"
    | "/ledger"
    | "/policy"
    | "/projects"
    | "/pulse"
    | "/reminders"
    | "/settings"
    | "/tuning"
    | "/watch-floor"
    | "/workflows"
    | "/cases/$caseId"
    | "/channels/$channelId"
    | "/lanes/$laneId"
    | "/messages/new"
    | "/projects/$projectId"
    | "/workflows/$workflowId"
    | "/channels/$channelId/posts/$postId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/agents"
    | "/gaps"
    | "/handoff"
    | "/leases"
    | "/ledger"
    | "/policy"
    | "/projects"
    | "/pulse"
    | "/reminders"
    | "/settings"
    | "/tuning"
    | "/watch-floor"
    | "/workflows"
    | "/cases/$caseId"
    | "/channels/$channelId"
    | "/lanes/$laneId"
    | "/messages/new"
    | "/projects/$projectId"
    | "/workflows/$workflowId"
    | "/channels/$channelId/posts/$postId";
  id:
    | "__root__"
    | "/"
    | "/agents"
    | "/gaps"
    | "/handoff"
    | "/leases"
    | "/ledger"
    | "/policy"
    | "/projects"
    | "/pulse"
    | "/reminders"
    | "/settings"
    | "/tuning"
    | "/watch-floor"
    | "/workflows"
    | "/cases/$caseId"
    | "/channels/$channelId"
    | "/lanes/$laneId"
    | "/messages/new"
    | "/projects/$projectId"
    | "/workflows/$workflowId"
    | "/channels/$channelId/posts/$postId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
  agentsRoute: typeof agentsRoute;
  gapsRoute: typeof gapsRoute;
  handoffRoute: typeof handoffRoute;
  leasesRoute: typeof leasesRoute;
  ledgerRoute: typeof ledgerRoute;
  policyRoute: typeof policyRoute;
  projectsRoute: typeof projectsRoute;
  pulseRoute: typeof pulseRoute;
  remindersRoute: typeof remindersRoute;
  settingsRoute: typeof settingsRoute;
  tuningRoute: typeof tuningRoute;
  watchFloorRoute: typeof watchFloorRoute;
  workflowsRoute: typeof workflowsRoute;
  casesDotcaseIdRoute: typeof casesDotcaseIdRoute;
  channelsDotchannelIdRoute: typeof channelsDotchannelIdRoute;
  lanesDotlaneIdRoute: typeof lanesDotlaneIdRoute;
  messagesDotnewRoute: typeof messagesDotnewRoute;
  projectsDotprojectIdRoute: typeof projectsDotprojectIdRoute;
  workflowsDotworkflowIdRoute: typeof workflowsDotworkflowIdRoute;
  channelsDotchannelIdDotpostsDotpostIdRoute: typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/workflows": {
      id: "/workflows";
      path: "/workflows";
      fullPath: "/workflows";
      preLoaderRoute: typeof workflowsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/watch-floor": {
      id: "/watch-floor";
      path: "/watch-floor";
      fullPath: "/watch-floor";
      preLoaderRoute: typeof watchFloorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tuning": {
      id: "/tuning";
      path: "/tuning";
      fullPath: "/tuning";
      preLoaderRoute: typeof tuningRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof settingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reminders": {
      id: "/reminders";
      path: "/reminders";
      fullPath: "/reminders";
      preLoaderRoute: typeof remindersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pulse": {
      id: "/pulse";
      path: "/pulse";
      fullPath: "/pulse";
      preLoaderRoute: typeof pulseRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects": {
      id: "/projects";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof projectsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/policy": {
      id: "/policy";
      path: "/policy";
      fullPath: "/policy";
      preLoaderRoute: typeof policyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/ledger": {
      id: "/ledger";
      path: "/ledger";
      fullPath: "/ledger";
      preLoaderRoute: typeof ledgerRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/leases": {
      id: "/leases";
      path: "/leases";
      fullPath: "/leases";
      preLoaderRoute: typeof leasesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/handoff": {
      id: "/handoff";
      path: "/handoff";
      fullPath: "/handoff";
      preLoaderRoute: typeof handoffRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/gaps": {
      id: "/gaps";
      path: "/gaps";
      fullPath: "/gaps";
      preLoaderRoute: typeof gapsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/agents": {
      id: "/agents";
      path: "/agents";
      fullPath: "/agents";
      preLoaderRoute: typeof agentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/workflows/$workflowId": {
      id: "/workflows/$workflowId";
      path: "/workflows/$workflowId";
      fullPath: "/workflows/$workflowId";
      preLoaderRoute: typeof workflowsDotworkflowIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/$projectId": {
      id: "/projects/$projectId";
      path: "/projects/$projectId";
      fullPath: "/projects/$projectId";
      preLoaderRoute: typeof projectsDotprojectIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/messages/new": {
      id: "/messages/new";
      path: "/messages/new";
      fullPath: "/messages/new";
      preLoaderRoute: typeof messagesDotnewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/lanes/$laneId": {
      id: "/lanes/$laneId";
      path: "/lanes/$laneId";
      fullPath: "/lanes/$laneId";
      preLoaderRoute: typeof lanesDotlaneIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/channels/$channelId": {
      id: "/channels/$channelId";
      path: "/channels/$channelId";
      fullPath: "/channels/$channelId";
      preLoaderRoute: typeof channelsDotchannelIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/cases/$caseId": {
      id: "/cases/$caseId";
      path: "/cases/$caseId";
      fullPath: "/cases/$caseId";
      preLoaderRoute: typeof casesDotcaseIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/channels/$channelId/posts/$postId": {
      id: "/channels/$channelId/posts/$postId";
      path: "/channels/$channelId/posts/$postId";
      fullPath: "/channels/$channelId/posts/$postId";
      preLoaderRoute: typeof channelsDotchannelIdDotpostsDotpostIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  agentsRoute: agentsRoute,
  gapsRoute: gapsRoute,
  handoffRoute: handoffRoute,
  leasesRoute: leasesRoute,
  ledgerRoute: ledgerRoute,
  policyRoute: policyRoute,
  projectsRoute: projectsRoute,
  pulseRoute: pulseRoute,
  remindersRoute: remindersRoute,
  settingsRoute: settingsRoute,
  tuningRoute: tuningRoute,
  watchFloorRoute: watchFloorRoute,
  workflowsRoute: workflowsRoute,
  casesDotcaseIdRoute: casesDotcaseIdRoute,
  channelsDotchannelIdRoute: channelsDotchannelIdRoute,
  lanesDotlaneIdRoute: lanesDotlaneIdRoute,
  messagesDotnewRoute: messagesDotnewRoute,
  projectsDotprojectIdRoute: projectsDotprojectIdRoute,
  workflowsDotworkflowIdRoute: workflowsDotworkflowIdRoute,
  channelsDotchannelIdDotpostsDotpostIdRoute:
    channelsDotchannelIdDotpostsDotpostIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
