apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ambush-engine.fullname" . }}
  labels:
    {{- include "ambush-engine.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ include "ambush-engine.renderConfig" . | nindent 4 }}
