{{- if and .Values.secrets.enabled (not .Values.secrets.existingSecret) (gt (len .Values.secrets.files) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ambush-engine.secretName" . }}
  labels:
    {{- include "ambush-engine.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $value := .Values.secrets.files }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
{{- end }}
