apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "swarm-team-six.fullname" . }}
  labels:
    {{- include "swarm-team-six.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ include "swarm-team-six.renderConfig" . | nindent 4 }}
