//! Phase 287 FUZZ-01: the untrusted Tetragon (gRPC/protobuf) telemetry-parse
//! boundary.
//!
//! `TetragonClient::get_events` streams `proto::GetEventsResponse` off the
//! wire; `<GetEventsResponse as prost::Message>::decode` (from
//! `swarm_ingest_tetragon::client::proto`, generated by `tonic::include_proto!`
//! over `proto/tetragon.proto`) is the actual protobuf decode of that
//! untrusted wire data, and `swarm_ingest_tetragon::mapper::map_process_exec`
//! is the real normalizer `bridge.rs` calls on a decoded `ProcessExec`
//! event. Re-verified at HEAD: both are already `pub`, no production
//! visibility change needed for this target.
//!
//! Exercising decode-then-map on the SAME arbitrary bytes matters here more
//! than for the other two targets: `map_process_exec` reads directly off
//! `Option` fields prost leaves unset for absent wrapper types
//! (`google.protobuf.UInt32Value uid`, `Timestamp start_time`, absent
//! `parent`), and it is exactly that combination -- a wire message the
//! decoder accepts but with fields an attacker can freely omit or zero out
//! -- this harness needs the real decode to produce, not something built by
//! hand in the harness.
//!
//! `decode` returning `Err(DecodeError)` (truncated varint, unknown wire
//! type, bad tag) is an expected rejection. `map_process_exec` returning
//! `None` (no `process` field) is likewise documented, expected behaviour
//! (see its `missing_process_returns_none` test). Only a panic or other UB
//! is a finding.
#![no_main]

use libfuzzer_sys::fuzz_target;
use prost::Message;
use swarm_ingest_tetragon::client::proto;
use swarm_ingest_tetragon::mapper::map_process_exec;

fuzz_target!(|data: &[u8]| {
    let Ok(response) = proto::GetEventsResponse::decode(data) else {
        return;
    };

    if let Some(proto::get_events_response::Event::ProcessExec(exec)) = response.event {
        let _ = map_process_exec(&exec, &response.node_name);
    }
});
